"use strict";
/**
 * Export File Service — shared persistence + serving for generated
 * enterprise export files (DOCX/PPTX/ZIP/etc).
 *
 * Enterprise Capability Expansion mission. Multiple new export capabilities
 * (DOCX, PPTX, ZIP project bundles) all need the same thing: take real
 * generated bytes, persist them somewhere fetchable, and return a URL. This
 * is the ONE place that logic lives — reused by every exporter below rather
 * than each one reinventing local-disk-write-plus-serving-route (which is
 * exactly what the prior mission's TTS audio route did ad hoc; this
 * generalizes and replaces that duplication going forward).
 *
 * Reuses, does not duplicate:
 *   - storageService.cjs — real S3/R2 upload when cloud storage is
 *     configured (detectProvider().configured === true); this service
 *     never talks to a cloud provider directly.
 *   - creativeAssetLibrary.cjs — every persisted export is also recorded as
 *     a real "document" asset (ASSET_TYPES already includes "document"),
 *     so exports show up in the same asset library as images/voice/video,
 *     not a separate, parallel tracking system.
 *
 * When cloud storage isn't configured (the common case in dev/self-hosted
 * installs — verified unconfigured in this environment), falls back to
 * local disk under data/exports/, served via the generic
 * GET /exports/:orgScope/:filename route in backend/routes/exportFiles.js.
 * Every write is org-scoped by directory (never a shared flat namespace),
 * consistent with the org-isolation pattern already established for the
 * connector vault (secretVault.cjs) and myConnectors.js.
 */

const fs   = require("fs");
const path = require("path");

const _try = fn => { try { return fn(); } catch { return null; } };
const _storage = () => _try(() => require("./storageService.cjs"));
const _assets  = () => _try(() => require("./creativeAssetLibrary.cjs"));

const EXPORT_ROOT = path.join(__dirname, "../../data/exports");
const GLOBAL_SCOPE = "global";

function _safeScope(orgId) {
    // Directory-per-org, same purpose as secretVault's orgId namespacing —
    // one tenant can never read another tenant's export directory even by
    // guessing filenames, because the scope segment is server-derived
    // (req.user's real org, never a client-supplied path component).
    const s = String(orgId || GLOBAL_SCOPE).replace(/[^A-Za-z0-9_-]/g, "_");
    return s || GLOBAL_SCOPE;
}

function _safeFilename(name) {
    // Strips any path component — only a bare filename is ever accepted,
    // regardless of what the caller passes.
    const base = path.basename(String(name || ""));
    return base.replace(/[^A-Za-z0-9_.-]/g, "_") || `file_${Date.now()}`;
}

/**
 * persist(buffer, { filename, mimeType, orgId, accountId, capability, tags })
 * Writes real bytes to durable storage and records them as a real asset.
 * @returns {{ url, filename, orgScope, sizeBytes, storedVia }}
 */
async function persist(buffer, opts = {}) {
    if (!Buffer.isBuffer(buffer)) throw new Error("persist() requires a real Buffer of file bytes");
    if (!buffer.length) throw new Error("persist() refuses to store an empty buffer — no fake/placeholder files");

    const filename = _safeFilename(opts.filename);
    const orgScope = _safeScope(opts.orgId);
    let url = null;
    let storedVia = null;

    const storage = _storage();
    const provider = storage?.detectProvider?.();
    if (provider?.configured) {
        try {
            const key = `exports/${orgScope}/${filename}`;
            await storage.upload(key, buffer, opts.mimeType || "application/octet-stream");
            url = storage.signedUrl(key);
            storedVia = provider.provider;
        } catch (e) {
            // Real cloud upload failure — fall through to local disk rather
            // than silently losing the file or fabricating a URL.
            storedVia = null;
        }
    }

    if (!url) {
        const dir = path.join(EXPORT_ROOT, orgScope);
        fs.mkdirSync(dir, { recursive: true });
        fs.writeFileSync(path.join(dir, filename), buffer);
        url = `/exports/${orgScope}/${filename}`;
        storedVia = "local";
    }

    // Record as a real asset in the same library images/voice/video use —
    // "document" is already a defined ASSET_TYPE in creativeAssetLibrary.cjs.
    _try(() => _assets()?.storeAsset({
        type: "document",
        prompt: opts.capability || "export",
        provider: storedVia,
        capability: opts.capability || "file_export",
        url,
        mimeType: opts.mimeType || "application/octet-stream",
        accountId: opts.accountId || null,
        orgId: opts.orgId || null,
        tags: opts.tags || [],
        folder: opts.folder || "exports",
        metadata: { filename, sizeBytes: buffer.length, storedVia },
    }));

    return { url, filename, orgScope, sizeBytes: buffer.length, storedVia };
}

/**
 * resolveLocal(orgScope, filename) — used only by the local-serving route.
 * Returns the real absolute path if it exists inside EXPORT_ROOT, or null.
 * Guards against path traversal even though both inputs are already
 * sanitized by the route's own regex validation (defense in depth).
 */
function resolveLocal(orgScope, filename) {
    const scope = _safeScope(orgScope);
    const name  = _safeFilename(filename);
    const abs   = path.join(EXPORT_ROOT, scope, name);
    const scopeDir = path.join(EXPORT_ROOT, scope);
    if (!abs.startsWith(scopeDir + path.sep) && abs !== scopeDir) return null;
    return fs.existsSync(abs) ? abs : null;
}

module.exports = { persist, resolveLocal, EXPORT_ROOT };
