"use strict";
/**
 * innovationEngine.cjs — POST-Ω P18 Scientific Discovery Engine
 *
 * Tracks validated discoveries, algorithm improvements, benchmark improvements,
 * and platform innovations generated by the scientific discovery pipeline.
 *
 * Reuses: experimentOrchestratorEngine, hypothesisEngine, publicationEngine,
 *         engineeringBenchmarkEngine, selfImprovementEngine,
 *         researchKnowledgeEngine, evolutionReasoningEngine,
 *         knowledgeReasoningEngine, digitalTwinEngine.
 *
 * Storage: data/innovations.json
 */

const fs   = require("fs");
const path = require("path");
const ROOT = path.join(__dirname, "../..");
const DATA = path.join(ROOT, "data", "innovations.json");

const _try = fn => { try { return fn(); } catch { return null; } };

const _eoe = () => _try(() => require("./experimentOrchestratorEngine.cjs"));
const _hyp = () => _try(() => require("./hypothesisEngine.cjs"));
const _pub = () => _try(() => require("./publicationEngine.cjs"));
const _eb  = () => _try(() => require("./engineeringBenchmarkEngine.cjs"));
const _sie = () => _try(() => require("./selfImprovementEngine.cjs"));
const _rke = () => _try(() => require("./researchKnowledgeEngine.cjs"));
const _ose = () => _try(() => require("./evolutionReasoningEngine.cjs"));
const _okb = () => _try(() => require("./knowledgeReasoningEngine.cjs"));

function _ts() { return new Date().toISOString(); }
function _id() { return `inn_${Date.now()}_${Math.random().toString(36).slice(2,6)}`; }

const INNOVATION_TYPES = [
  "validated_discovery",
  "algorithm_improvement",
  "benchmark_improvement",
  "platform_innovation",
];

const IMPACT_LEVELS = ["low", "medium", "high", "breakthrough"];

// ── Storage ───────────────────────────────────────────────────────────────────

function _load() {
  const defaults = {
    innovations: [],
    stats: {
      total: 0, byType: {}, byImpact: {},
      innovationScore: 0, breakthroughs: 0,
    },
    updatedAt: null,
  };
  try {
    const d = JSON.parse(fs.readFileSync(DATA, "utf8"));
    if (!Array.isArray(d.innovations)) return defaults;
    return d;
  } catch { return defaults; }
}

function _save(d) {
  fs.mkdirSync(path.dirname(DATA), { recursive: true });
  if (d.innovations.length > 2000) d.innovations = d.innovations.slice(-2000);
  d.updatedAt = _ts();
  fs.writeFileSync(DATA, JSON.stringify(d, null, 2));
}

function _computeStats(innovations) {
  const byType   = {};
  const byImpact = {};
  INNOVATION_TYPES.forEach(t => { byType[t] = 0; });
  IMPACT_LEVELS.forEach(l => { byImpact[l] = 0; });
  innovations.forEach(inn => {
    if (byType[inn.type]     !== undefined) byType[inn.type]++;
    if (byImpact[inn.impact] !== undefined) byImpact[inn.impact]++;
  });
  const breakthroughs  = byImpact.breakthrough || 0;
  const high           = byImpact.high || 0;
  const innovationScore = Math.min(100, Math.round(
    breakthroughs * 20 + high * 10 +
    (byImpact.medium || 0) * 5 +
    (byImpact.low || 0) * 2
  ));
  return { total: innovations.length, byType, byImpact, innovationScore, breakthroughs };
}

// ── Discovery: scan platform for innovations ──────────────────────────────────

function _discoverAlgorithmImprovements() {
  const improvements = [];
  try {
    const pats = _sie()?.discoverPatterns?.() || {};
    const promoted = (pats.patterns || []).filter(p => p.action === "promote_fix" && p.confidence >= 85);
    promoted.forEach(p => {
      improvements.push({
        type:        "algorithm_improvement",
        title:       `Self-Healing Algorithm: ${p.pattern.slice(0, 60)}`,
        description: p.suggestion || p.pattern,
        evidence:    p.evidence,
        confidence:  p.confidence,
        impact:      p.confidence >= 95 ? "high" : "medium",
        source:      "selfImprovementEngine",
      });
    });
  } catch {}
  return improvements;
}

function _discoverBenchmarkImprovements() {
  const improvements = [];
  try {
    const cmp = _eb()?.compareToBaseline?.() || {};
    const dims = cmp.dimensions || [];
    dims.forEach(d => {
      const delta = (d.score || d.current || 0) - (d.baseline || 70);
      if (delta > 5) {
        improvements.push({
          type:        "benchmark_improvement",
          title:       `${d.name || d.dimension} improved by ${delta} points`,
          description: `Benchmark dimension '${d.name || d.dimension}' scored ${d.score || d.current} vs baseline ${d.baseline || 70}.`,
          evidence:    1,
          confidence:  90,
          impact:      delta > 20 ? "high" : delta > 10 ? "medium" : "low",
          source:      "engineeringBenchmarkEngine",
          delta,
        });
      }
    });
  } catch {}
  return improvements;
}

function _discoverFromExperiments() {
  const discoveries = [];
  try {
    const exps = _eoe()?.listExperiments?.({ outcome: "hypothesis_supported", limit: 20 }) || {};
    (exps.experiments || []).forEach(exp => {
      discoveries.push({
        type:        "validated_discovery",
        title:       `Validated: ${(exp.hypothesisStatement || 'Discovery').slice(0, 60)}`,
        description: `Experiment ${exp.id} confirmed hypothesis with ${exp.confidence}% confidence.`,
        evidence:    exp.evidenceCount || 1,
        confidence:  exp.confidence || 80,
        impact:      exp.confidence >= 90 ? "high" : exp.confidence >= 80 ? "medium" : "low",
        source:      "experimentOrchestratorEngine",
        experimentId: exp.id,
      });
    });
  } catch {}
  return discoveries;
}

function _discoverPlatformInnovations() {
  const innovations = [];
  try {
    const ose = _ose()?.analyze?.() || {};
    const recs = (ose.recommendations || ose.insights || []).slice(0, 3);
    recs.forEach(r => {
      innovations.push({
        type:        "platform_innovation",
        title:       `Platform Innovation: ${(r.recommendation || r.insight || 'AI Evolution').slice(0, 60)}`,
        description: r.recommendation || r.insight || "AI-driven platform improvement identified.",
        evidence:    1,
        confidence:  r.confidence || 78,
        impact:      r.confidence >= 90 ? "breakthrough" : r.confidence >= 80 ? "high" : "medium",
        source:      "evolutionReasoningEngine",
      });
    });

    // RKE radar innovations
    const radar = _rke()?.getRadar?.() || {};
    (radar.entries || []).filter(e => e.ring === "adopt").slice(0, 2).forEach(e => {
      innovations.push({
        type:        "platform_innovation",
        title:       `Technology Adoption: ${e.name || e.topic}`,
        description: e.description || `${e.name} is ready for adoption in the platform.`,
        evidence:    1,
        confidence:  88,
        impact:      "medium",
        source:      "researchKnowledgeEngine",
      });
    });
  } catch {}
  return innovations;
}

// ── Core: scan ────────────────────────────────────────────────────────────────

function scan() {
  const raw = [
    ..._discoverAlgorithmImprovements(),
    ..._discoverBenchmarkImprovements(),
    ..._discoverFromExperiments(),
    ..._discoverPlatformInnovations(),
  ];

  const innovations = raw.map(inn => ({
    id:           _id(),
    type:         inn.type,
    title:        inn.title,
    description:  inn.description,
    evidence:     inn.evidence || 1,
    confidence:   inn.confidence || 75,
    impact:       inn.impact || "low",
    source:       inn.source,
    experimentId: inn.experimentId || null,
    delta:        inn.delta || null,
    discoveredAt: _ts(),
    appliedAt:    null,
    applied:      false,
  }));

  const d = _load();
  const dedup = new Map(d.innovations.map(i => [i.title.slice(0, 50), i]));
  innovations.forEach(i => dedup.set(i.title.slice(0, 50), i));
  d.innovations = [...dedup.values()];
  d.stats = _computeStats(d.innovations);
  _save(d);

  return {
    ok:              true,
    discovered:      innovations.length,
    total:           d.innovations.length,
    innovationScore: d.stats.innovationScore,
    innovations,
  };
}

function recordInnovation(spec) {
  if (!spec.title || !spec.type) return { ok: false, error: "title and type are required" };
  if (!INNOVATION_TYPES.includes(spec.type)) return { ok: false, error: `Unknown type: ${spec.type}` };
  const innovation = {
    id:           _id(),
    type:         spec.type,
    title:        spec.title,
    description:  spec.description || "",
    evidence:     spec.evidence || 1,
    confidence:   spec.confidence || 75,
    impact:       IMPACT_LEVELS.includes(spec.impact) ? spec.impact : "low",
    source:       spec.source || "manual",
    experimentId: spec.experimentId || null,
    delta:        spec.delta || null,
    discoveredAt: _ts(),
    appliedAt:    null,
    applied:      false,
  };
  const d = _load();
  d.innovations.push(innovation);
  d.stats = _computeStats(d.innovations);
  _save(d);
  return { ok: true, innovation };
}

function markApplied(id) {
  const d = _load();
  const inn = d.innovations.find(i => i.id === id);
  if (!inn) return { ok: false, error: `Innovation ${id} not found` };
  inn.applied   = true;
  inn.appliedAt = _ts();
  d.stats = _computeStats(d.innovations);
  _save(d);
  return { ok: true, innovation: inn };
}

function getInnovation(id) {
  return _load().innovations.find(i => i.id === id) || null;
}

function listInnovations({ type, impact, applied, limit = 50 } = {}) {
  let items = _load().innovations;
  if (type)                       items = items.filter(i => i.type === type);
  if (impact)                     items = items.filter(i => i.impact === impact);
  if (applied !== undefined)      items = items.filter(i => i.applied === applied);
  return { ok: true, innovations: items.slice(0, limit), total: items.length };
}

function getStats() {
  const d = _load();
  return { ...d.stats, INNOVATION_TYPES, IMPACT_LEVELS, updatedAt: d.updatedAt };
}

module.exports = {
  INNOVATION_TYPES,
  IMPACT_LEVELS,
  scan,
  recordInnovation,
  markApplied,
  getInnovation,
  listInnovations,
  getStats,
};
