import React from "react";
import { useNavigate } from "react-router-dom";

export default function Terms() {
  const navigate = useNavigate();

  return (
    <>
      <header className="mobile-header">
        <button
          onClick={() => navigate(-1)}
          style={{ color: "var(--accent)", fontWeight: 600, fontSize: 15 }}
        >
          ← Back
        </button>
        <span style={{ fontWeight: 700, fontSize: 16 }}>Terms & Conditions</span>
        <span style={{ width: 60 }} />
      </header>

      <div className="app-screen">
        <div className="legal-page selectable">
          <h1>Terms &amp; Conditions</h1>
          <p className="updated">Last updated: May 2026</p>

          <p>
            By downloading, installing, or using JARVIS AI (the "App"), you
            agree to be bound by these Terms and Conditions. If you do not agree,
            do not use the App.
          </p>

          <h2>1. Description of Service</h2>
          <p>
            JARVIS AI is a business automation assistant that provides AI-powered
            chat, task generation, CRM management, and payment tooling. The App
            connects to a hosted backend service to deliver these features.
          </p>

          <h2>2. Eligibility</h2>
          <p>
            You must be at least 18 years old and capable of forming a legally
            binding contract to use this App. By using it, you represent that you
            meet these requirements.
          </p>

          <h2>3. Account Responsibility</h2>
          <ul>
            <li>You are responsible for maintaining the security of your account credentials.</li>
            <li>You must notify us immediately of any unauthorised use of your account.</li>
            <li>You are responsible for all activity that occurs under your account.</li>
          </ul>

          <h2>4. Acceptable Use</h2>
          <p>You agree not to use JARVIS AI to:</p>
          <ul>
            <li>Violate any applicable law or regulation.</li>
            <li>Send spam, unsolicited messages, or harass others.</li>
            <li>Transmit malicious code or attempt to compromise our systems.</li>
            <li>Collect or harvest personal data of others without consent.</li>
            <li>Misrepresent your identity or impersonate others.</li>
          </ul>

          <h2>5. AI-Generated Content</h2>
          <p>
            Responses generated by JARVIS AI are produced by third-party AI
            models (Groq, OpenAI). We do not guarantee the accuracy, completeness,
            or fitness for any particular purpose of AI-generated content. You are
            solely responsible for how you use AI outputs.
          </p>

          <h2>6. Payment Processing</h2>
          <p>
            Payment links generated through the App are processed by Razorpay.
            By generating payment links, you agree to Razorpay's Terms of Service.
            We are not responsible for payment disputes or failed transactions.
          </p>

          <h2>7. WhatsApp Messaging</h2>
          <p>
            You are solely responsible for ensuring you have valid consent to
            message any phone number via the follow-up tool. Misuse may violate
            WhatsApp Business Policy and applicable anti-spam laws.
          </p>

          <h2>8. Intellectual Property</h2>
          <p>
            The JARVIS AI app, its design, code, and branding are the property
            of the developer. You are granted a limited, non-exclusive,
            non-transferable licence to use the App for its intended purpose.
          </p>

          <h2>9. Disclaimer of Warranties</h2>
          <p>
            The App is provided "as is" without warranties of any kind. We do
            not warrant that the App will be uninterrupted, error-free, or free
            of harmful components.
          </p>

          <h2>10. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, we shall not be liable for
            any indirect, incidental, special, or consequential damages arising
            from your use of the App.
          </p>

          <h2>11. Termination</h2>
          <p>
            We reserve the right to terminate or suspend your access at any time,
            without notice, for conduct that we believe violates these Terms or
            is harmful to other users, us, or third parties.
          </p>

          <h2>12. Changes to Terms</h2>
          <p>
            We may update these Terms at any time. Continued use of the App after
            changes constitutes acceptance of the new Terms.
          </p>

          <h2>13. Contact</h2>
          <p>
            For questions about these Terms, contact us at:{" "}
            <a href="mailto:altamashjauhar@gmail.com">altamashjauhar@gmail.com</a>
          </p>

          <div style={{ height: 32 }} />
        </div>
      </div>
    </>
  );
}
